package com.mycompany.Classes;

import org.apache.poi.*;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LL
 */

public class ClientsJFrame extends javax.swing.JFrame {
DefaultTableModel model;
exportTable export = new exportTable();
    /**
     * Creates new form ClientsJFrame
     */
    public void search(String str){
    model = (DefaultTableModel) ClientsTable.getModel();
    TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
    ClientsTable.setRowSorter(trs);
    trs.setRowFilter(RowFilter.regexFilter(str));
}
    
    public void currentDate(){
    GregorianCalendar cal = new GregorianCalendar();
    int month =cal.get(Calendar.MONTH);
    int day =cal.get(Calendar.DAY_OF_MONTH);
    int year = cal.get(Calendar.YEAR);
        date.setText(day+"/"+(month+1)+"/"+year);
    }
    public ClientsJFrame() {
        initComponents();
    show_clients();
    currentDate();
    }
    public ArrayList<Clients>opakovki(){
    ArrayList<Clients> list = new ArrayList<>();
    try{
            //Class.forName("com.mysql.jdbc.Driver");
            //Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/demo", "root", "admin123");
           // Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            //Connection conn = DriverManager.getConnection("jdbc:derby:D:\\Projects\\data");
            Class.forName("org.h2.Driver");
             Connection conn = DriverManager.getConnection("jdbc:h2:./database/db;IFEXISTS=TRUE","test","test");
            char statusx='X';
            char statusy='Y';
            boolean isAve= false;
            
            String query1 = "SELECT * FROM opakovki\n" +
"WHERE opakovki.Status ='"+statusx+"'";
            
            Statement stm = conn.createStatement();
            ResultSet rs = stm.executeQuery(query1);
            Sklad vsichki = null;
            while(rs.next()){
                Clients clients = new Clients(rs.getString("IDopakovka"),rs.getString("Status")
                        ,rs.getString("Location"),rs.getString("datestamp"),rs.getString("numWh"));
            list.add(clients);}
            
    }
    catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
    }
     return list;}
    public void show_clients(){
    ArrayList<Clients>list1 = opakovki();
    DefaultTableModel model = (DefaultTableModel) ClientsTable.getModel();
   
    Object[] row = new Object[5];
    for (int i = 0; i < list1.size(); i++) {
        row[0]= list1.get(i).getNumWh();
        row[1] = list1.get(i).getID();
        row[2] = list1.get(i).getStatus();
        row[3] = list1.get(i).getLocation();
        row[4]= list1.get(i).getdatestamp();
        model.addRow(row);}
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ClientsTable = new javax.swing.JTable();
        pdf = new javax.swing.JButton();
        saveAs = new javax.swing.JButton();
        refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("Търсене:");

        search.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });

        date.setBackground(new java.awt.Color(0, 102, 102));
        date.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        date.setForeground(new java.awt.Color(204, 255, 204));

        ClientsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Складова Разписка", "Опаковка/и", "Статус", "Клиент", "Дата/час"
            }
        ));
        jScrollPane1.setViewportView(ClientsTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addGap(268, 268, 268)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pdf.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        pdf.setText(".pdf");
        pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfActionPerformed(evt);
            }
        });

        saveAs.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        saveAs.setText("Таблица");
        saveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsActionPerformed(evt);
            }
        });

        refresh.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        refresh.setText("Обнови");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(saveAs, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refresh, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pdf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(pdf, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(saveAs, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(refresh, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        String searched = search.getText();
        search(searched);
    }//GEN-LAST:event_searchKeyReleased

    private void pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfActionPerformed
        try {
            export.exportPdf(ClientsTable);
        } catch (IOException ex) {
            Logger.getLogger(AllJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pdfActionPerformed

    private void saveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsActionPerformed

        try {
            export.export(ClientsTable);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_saveAsActionPerformed
public void refreshInfo() throws ClassNotFoundException, SQLException{
   DefaultTableModel model = (DefaultTableModel)ClientsTable.getModel();
   model.setRowCount(0);
   show_clients();}
    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        try {
            refreshInfo();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CommentsJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CommentsJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_refreshActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ClientsTable;
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pdf;
    private javax.swing.JButton refresh;
    private javax.swing.JButton saveAs;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
